### PR TITLE
update readme file (adding usage of HuggingFace model)

### PR DESCRIPTION
**Pull request by mao-code**
Based on [this issue](https://github.com/haotian-liu/LLaVA/issues/402)
I found that the contents of documents that describe the usage of LLaVA series model via HuggingFace are not that clear.
Therefore, I would like to add these information directly in the readme file. Hope that it can help someone who struggle with it.
If there are any mistakes, please correct me!
Thanks!

### CODE REVIEW

**Comment by wm-mask** [comment]
Thanks for the PR! I have a quick question, where do the models get saved? I can't find them. Thank you 🙏

**Comment by wm-mask** [comment]
Thanks for your reply. Sorry it's not clear.
When you say it's the hugging face model path, do you pass to it just the `"liuhaotian/LLaVA-Lightning-MPT-7B-preview"` name of the model? or do you pass the local path to where the model is cached by huggingface?


Also when you say "load_from_pretrained" do you mean you change some function in the code somewhere? Or just to load the model the first time for huggingface to cache it?

I followed your updated README

**Comment by mao-code** [comment]
@wm-mask Yes, the model path I used is just the hugging face model path. For the example model, it is just “liuhaotian/LLaVA-Lightning-MPT-7B-preview”.

And the load_from_pretrain is a function I import within this repository. I didn’t change anything.

**Comment by mao-code** [comment]
@wm-mask For the second part of the content that I update in the read me file, I import the eval function as I mentioned in the readme.

By doing so, you can use it to “inference” directly using the eval function.

For more detail, you can check these functions in the repository.

**Comment by haotian-liu** [comment]
Sorry for the late response. I like the idea of adding the quick start scripts, made a few mods to the language and change it the llava-v1.5-7b model in the example. Also used the collapse toggle to avoid displaying large amount of code in README. Thank you!

**Pull request merged**
