### PR TITLE
Add stopping criteria for gradio model_worker

### PR DESCRIPTION
**Pull request by HTplex**
Added stopping criteria for model_worker to eliminate self-repeating responses in gradio demo.

### CODE REVIEW

**Comment by haotian-liu** [comment]
Hi, thanks for the contribution.
I wonder if you can provide which model, an example image and instruction for us to test?

Also, is it related to https://github.com/haotian-liu/LLaVA/issues/1086#issuecomment-1928936542?

Thank you again!

**Comment by HTplex** [comment]
I was testing on llava-v1.6-34b but this would fix every model worker that's spawned using serve/model_worker.py, including #1086.

The first example image and prompt (ironing on taxi) on llava-v1.6-34b should be good for testing purposes, the model would start talking about random stuff and adding random symbols after answering the actual question. 
Screenshot 2024-02-06 at 16 36 12

**Comment by haotian-liu** [comment]
Hi, can you share the command you used to spawn the workers/demo servers? I could not reproduce that on my side. Thanks.

**Comment by HTplex** [comment]
Sorry I did't mentioned the quantizations.
```
CUDA_VISIBLE_DEVICES=0,1 python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path /data/0001.llava-v1.6-34b/ --load-4bit
```

**Comment by HTplex** [comment]
Yes, the demo your link doesn't seems to have the repetition issue.

**Comment by HTplex** [comment]
Some extra information of my environment with reproducible repetition on latest code: Nvidia A10*4 with Driver Version: 545.23.08    CUDA Version: 12.3, clip_vit manually downloaded from huggingface and changed vision_tower in config file to relink. I haven't dig deeper yet but seems to me the problem is coming from [this commit](https://github.com/haotian-liu/LLaVA/commit/da83c48cb0679155b82dbf4603229bb7ce4929d4#diff-1d1c0310b9314b4e8f48deee17c086e864180f6a5f51c0198887f95b6c45e2d2) not working for some cases and I'm just reverting it.
[env.txt](https://github.com/haotian-liu/LLaVA/files/14184215/env.txt)

**Comment by haotian-liu** [comment]
one thing to debug. can you share your gradio_web_server logs?

**Comment by HTplex** [comment]
`2024-02-07 01:06:54 | INFO | gradio_web_server | load_demo. ip: 127.0.0.1
2024-02-07 01:06:54 | INFO | gradio_web_server | Models: []
2024-02-07 01:06:54 | ERROR | stderr | /root/miniconda3/envs/llava/lib/python3.10/site-packages/gradio/components/dropdown.py:163: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include:  or set allow_custom_value=True.
2024-02-07 01:06:54 | ERROR | stderr |   warnings.warn(
2024-02-07 01:09:12 | INFO | gradio_web_server | load_demo. ip: 127.0.0.1
2024-02-07 01:09:12 | INFO | gradio_web_server | Models: ['0001.llava-v1.6-34b']
2024-02-07 01:09:15 | INFO | gradio_web_server | add_text. ip: 127.0.0.1. len: 33
2024-02-07 01:09:16 | INFO | gradio_web_server | http_bot. ip: 127.0.0.1
2024-02-07 01:09:16 | INFO | gradio_web_server | model_name: 0001.llava-v1.6-34b, worker_addr: http://localhost:40000
2024-02-07 01:09:16 | INFO | gradio_web_server | ==== request ====
{'model': '0001.llava-v1.6-34b', 'prompt': '<|im_start|>system\nAnswer the questions.<|im_end|><|im_start|>user\n<image>\nWhat is unusual about this image?<|im_end|><|im_start|>assistant\n', 'temperature': 0.2, 'top_p': 0.7, 'max_new_tokens': 512, 'stop': '<|im_end|>', 'images': "List of 1 images: ['b939abf2c4553ce07e642170aee3a3d7']"}
2024-02-07 01:11:04 | INFO | gradio_web_server | add_text. ip: 127.0.0.1. len: 33
2024-02-07 01:11:06 | INFO | gradio_web_server | http_bot. ip: 127.0.0.1
2024-02-07 01:11:06 | INFO | gradio_web_server | model_name: 0001.llava-v1.6-34b, worker_addr: http://localhost:40000
2024-02-07 01:11:06 | INFO | gradio_web_server | ==== request ====
{'model': '0001.llava-v1.6-34b', 'prompt': '<|im_start|>system\nAnswer the questions.<|im_end|><|im_start|>user\n<image>\nWhat is unusual about this image?<|im_end|><|im_start|>assistant\n', 'temperature': 0.2, 'top_p': 0.7, 'max_new_tokens': 512, 'stop': '<|im_end|>', 'images': "List of 1 images: ['b939abf2c4553ce07e642170aee3a3d7']"}
2024-02-07 01:12:06 | INFO | gradio_web_server | The image depicts a man ironing a shirt while standing on a street, with a yellow vehicle in the background. The unusual aspect of this scene is that ironing clothes is typically done indoors, in a more controlled environment, such as a home or a professional laundry facility. The setting of the street is not a common place to iron clothes, and it's not a safe or practical location for this activity due to the potential for accidents and distractions from traffic. Additionally, the man is using a portable ironing board, which is not a typical piece of equipment one would expect to see on a city street.

The juxtaposition of the man ironing in the middle of the street with the urban backdrop creates a humorous and unexpected visual, which is likely the intention behind the scene. It's a staged photo meant to be amusing or thought-provoking, rather than depicting a real-life scenario.

Please note that the image is staged and not a depiction of a real event.

The image is a staged photo meant to be humorous or thought-provoking, rather than depicting a real-life scenario.

Please note that the image is staged and not a depiction of a real event.

Please note that the image is staged and not a depiction of a real-life scenario.

Please note that the image is staged and not a depiction of a real-life scenario.

Please note that the image is staged and not a depiction of a real-life scenario.

Please note that the image is staged and not a depiction of a real-life scenario.

Please note that the image is staged and not a depiction of a real-life scenario.

Please note that the image is staged and not a depiction of a real-life scenario.

Please note that the image is staged and not a depiction of a real-life scenario.

Please note that the image is staged and not a depiction of a real-life scenario.

Please note that the image is staged and not a depiction of a real-life scenario.

Please note that the image is staged and not a depiction of a real-life scenario.

Please note that the image is staged and not a depiction of a real-life scenario.

Please note that the image is staged and not a depiction of a real-life scenario.`

**Comment by haotian-liu** [comment]
Thanks for providing the additional information. I think I may know the cause -- if your model is local.

Can you check if this is the case? and what happens if you fix this mod: https://huggingface.co/liuhaotian/llava-v1.6-34b/commit/e2a1f782a20d26b855072029738bfd0107d85e96

**Comment by HTplex** [comment]
Repetition is fixed after updating generation_config.json, cheers.

**Comment by haotian-liu** [comment]
Great! I'll close this PR for now, thanks.

**Pull request closed without merging**
