### PR TITLE
Add vscode debug for the cli

### PR DESCRIPTION
**Pull request by mattmazzola**
Adds debug configuration for the `llava.serve.cli`

# Video Demo

https://github.com/haotian-liu/LLaVA/assets/2856501/3d7cac35-2201-4d48-9fa0-891287619447

### CODE REVIEW

**Comment by haotian-liu** [comment]
Hi Matt, thanks for the contribution. I feel that this PR may create some conflicts to the local env to the users (e.g. me), who has been already using `launch.json` for debugging, and it will be tricky to create new commits?

Please correct me if I am wrong, thanks.

**Comment by mattmazzola** [comment]
> may create some conflicts to the local env to the users (e.g. me), who has been already using launch.json for debugging

The `launch.json` I added was a _new_ file, meaning a previous `launch.json` didn't exist in the repo yet so there would not be any conflicts.  

The intention here was to ensure people had a working debug config to help the building of new features. However, if your workflow involves using a `launch.json` that is not committed to the repo and you don't want to worry about reverting changes or stashing changes to the file that would be committed in this PR then we can close the PR.  Given the heavy bias in contributions, it's likely better not to disrupt how you work.

**Comment by haotian-liu** [comment]
Thanks. I guess we can rename it to `launch.json.example` or `launch.example.json` (whichever follows the common practice)? How do you think?

**Comment by mattmazzola** [comment]
> How do you think?

I don't have much of preference between those two names. I think neither of those values would provide a default configuration for people to use. 

I think ideally you would commit the files you are using in the repo to the repo so it doesn't confuse other people.
Maybe at least add something to the `.vscode` folder or README which tells people not to add launch.json files

I will close the PR though since it's not worth introducing example file.

**Pull request closed without merging**
