### PR TITLE
Added support for inference using a Flask API

### PR DESCRIPTION
**Pull request by ashleykleynhans**

### CODE REVIEW

**Comment by dinchu** [comment]
Looks promising, but I would suggest some improvements:

-The demo processes the images in a way the model can work with them, the API fails with a lot of images since it doesn't do extra processing before the inference
-should work with the original worker/controller set, instead the API loads the model again
-I would suggest to use openAI API standards

**Comment by ashleykleynhans** [comment]
Its basically just the CLI script that is turned into an API, so all of that was already there and not done by me, you can suggest that to the original author, anyway this PR isn't getting merged or reviewed by the project owner so there is no point in wasting my time trying to contribute anything towards this project and the PR is now closed.

**Comment by dinchu** [comment]
I think your contribution is very valuable!

**Comment by hszhoushen** [comment]
I have a solution, add the code with flask (a web application package), so that the LLaVa model can be a server that can receive the post from any client, each time the model receives the post, it will process the image, and send back the language description to the client.

**Pull request closed without merging**
